<?php

namespace AppBundle\Repository;

/**
 * DatacenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatacenterRepository extends \Doctrine\ORM\EntityRepository
{
}
