<?php

namespace AppBundle\Repository;

/**
 * TypeInternetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeInternetRepository extends \Doctrine\ORM\EntityRepository
{
}
