<?php

namespace AppBundle\Repository;

/**
 * TypeServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeServerRepository extends \Doctrine\ORM\EntityRepository
{
}
