<?php

namespace AppBundle\Repository;

/**
 * TypeDatacenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDatacenterRepository extends \Doctrine\ORM\EntityRepository
{
}
