<?php

namespace AppBundle\Repository;

/**
 * TypeElectricityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeElectricityRepository extends \Doctrine\ORM\EntityRepository
{
}
